### ISSUE TITLE
Support both generations of IPMI headers

### ISSUE THREAD

**Issue by jimklimov** [networkupstools/nut#1175]
Some versions of IPMI headers had methods with "unsigned int (\*)" arguments, and others with "int (\*)" arguments. Our builds with heightened sensitivity to warnings fail on systems which do not match our variable types.

A hotfix was made in `drivers/Makefile.am` to ignore the warning for impacted source file: `nut_ipmipsu_CFLAGS = -Wnoerror=pointer-sign` but a better solution should be to detect the correct type in `configure` and use an appropriate `typedef` in our codebase for variable types or casting.

**Comment by jimklimov** [comment]
Excerpt from a build on Ubuntu 14.04:

````
[2021-11-11T21:47:48.648Z] depbase=`echo nut-libfreeipmi.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
[2021-11-11T21:47:48.648Z] 	/usr/lib/ccache/gcc-4.8 -DHAVE_CONFIG_H -I. -I../include   -I/srv/libvirt/abuild/jenkins-nut-altroots/jenkins-ubuntu1404-i386+ssh/workspace/nut_nut_release-notes-for-2.7.5/tmp/include -I../include  -D_LARGEFILE64_SOURCE -DNE_LFS -I/usr/include/neon     -I/usr/include/modbus   -I/srv/libvirt/abuild/jenkins-nut-altroots/jenkins-ubuntu1404-i386+ssh/workspace/nut_nut_release-notes-for-2.7.5/tmp/include -std=gnu99 -m32 -Wall -Wextra -Wsign-compare -pedantic -Werror -MT nut-libfreeipmi.o -MD -MP -MF $depbase.Tpo -c -o nut-libfreeipmi.o nut-libfreeipmi.c &&\
[2021-11-11T21:47:48.648Z] 	mv -f $depbase.Tpo $depbase.Po
[2021-11-11T21:47:48.648Z] nut-libfreeipmi.c: In function 'libfreeipmi_get_psu_info':
[2021-11-11T21:47:48.648Z] nut-libfreeipmi.c:417:4: error: pointer targets in passing argument 8 of 'ipmi_fru_parse_multirecord_power_supply_information' differ in signedness [-Werror=pointer-sign]
[2021-11-11T21:47:48.648Z]     &predictive_fail_tachometer_lower_threshold) < 0)
[2021-11-11T21:47:48.648Z]     ^
[2021-11-11T21:47:48.648Z] In file included from /usr/include/freeipmi/freeipmi.h:68:0,
[2021-11-11T21:47:48.648Z]                  from nut-libfreeipmi.c:46:
[2021-11-11T21:47:48.648Z] /usr/include/freeipmi/fru-parse/ipmi-fru-parse.h:183:5: note: expected 'unsigned int *' but argument is of type 'int *'
[2021-11-11T21:47:48.648Z]  int ipmi_fru_parse_multirecord_power_supply_information (ipmi_fru_parse_ctx_t ctx,
[2021-11-11T21:47:48.648Z]      ^
[2021-11-11T21:47:48.648Z] nut-libfreeipmi.c:417:4: error: pointer targets in passing argument 9 of 'ipmi_fru_parse_multirecord_power_supply_information' differ in signedness [-Werror=pointer-sign]
[2021-11-11T21:47:48.648Z]     &predictive_fail_tachometer_lower_threshold) < 0)
[2021-11-11T21:47:48.648Z]     ^
[2021-11-11T21:47:48.648Z] In file included from /usr/include/freeipmi/freeipmi.h:68:0,
[2021-11-11T21:47:48.648Z]                  from nut-libfreeipmi.c:46:
[2021-11-11T21:47:48.648Z] /usr/include/freeipmi/fru-parse/ipmi-fru-parse.h:183:5: note: expected 'unsigned int *' but argument is of type 'int *'
[2021-11-11T21:47:48.648Z]  int ipmi_fru_parse_multirecord_power_supply_information (ipmi_fru_parse_ctx_t ctx,
[2021-11-11T21:47:48.648Z]      ^
[2021-11-11T21:47:48.648Z] nut-libfreeipmi.c:417:4: error: pointer targets in passing argument 10 of 'ipmi_fru_parse_multirecord_power_supply_information' differ in signedness [-Werror=pointer-sign]
[2021-11-11T21:47:48.648Z]     &predictive_fail_tachometer_lower_threshold) < 0)
[2021-11-11T21:47:48.648Z]     ^
[2021-11-11T21:47:48.648Z] In file included from /usr/include/freeipmi/freeipmi.h:68:0,
[2021-11-11T21:47:48.648Z]                  from nut-libfreeipmi.c:46:
[2021-11-11T21:47:48.648Z] /usr/include/freeipmi/fru-parse/ipmi-fru-parse.h:183:5: note: expected 'unsigned int *' but argument is of type 'int *'
[2021-11-11T21:47:48.648Z]  int ipmi_fru_parse_multirecord_power_supply_information (ipmi_fru_parse_ctx_t ctx,
[2021-11-11T21:47:48.648Z]      ^
[2021-11-11T21:47:48.648Z] nut-libfreeipmi.c:417:4: error: pointer targets in passing argument 11 of 'ipmi_fru_parse_multirecord_power_supply_information' differ in signedness [-Werror=pointer-sign]
[2021-11-11T21:47:48.648Z]     &predictive_fail_tachometer_lower_threshold) < 0)
[2021-11-11T21:47:48.648Z]     ^
[2021-11-11T21:47:48.648Z] In file included from /usr/include/freeipmi/freeipmi.h:68:0,
[2021-11-11T21:47:48.648Z]                  from nut-libfreeipmi.c:46:
[2021-11-11T21:47:48.648Z] /usr/include/freeipmi/fru-parse/ipmi-fru-parse.h:183:5: note: expected 'unsigned int *' but argument is of type 'int *'
[2021-11-11T21:47:48.648Z]  int ipmi_fru_parse_multirecord_power_supply_information (ipmi_fru_parse_ctx_t ctx,
[2021-11-11T21:47:48.648Z]      ^
[2021-11-11T21:47:48.648Z] cc1: all warnings being treated as errors
[2021-11-11T21:47:48.648Z] make[1]: *** [nut-libfreeipmi.o] Error 1
[2021-11-11T21:47:48.648Z] make[1]: Target `all' not remade because of errors.
````

Build agent settings:
````
BUILD_TYPE="default-all-errors" BUILD_WARNOPT="hard" BUILD_WARNFATAL="yes" MAKE="make"  CC=gcc-4.8 CXX=g++-4.8 CPP=cpp-4.8 CFLAGS='-std=gnu99 -m32' CXXFLAGS='-std=gnu++98 -m32' LDFLAGS='-m32' ./ci_build.sh 
````

There were later a series of commits to hot-fix the "header incompatibility" up to https://github.com/networkupstools/nut/commit/9f508f236cf537c335d314d519abed0c4d6c5e92 as well as reconfigurations of the build agent for seemingly unrelated package installations, and recent builds with this scenario do not expose the problem. So part of the work to fix it would be to revert those hot-fixes, or maybe even again make some minimal OS/container setup, to have the problem visible.

**Comment by jimklimov** [comment]
Should get addressed by PR #1179
